<div>
<?php include 'heading.php';?>
</div>
<div class="menu">
<?php include 'menu.php';?>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
		<div>
		<?php include 'javamenu.php';?>
		</div>
    </div>
    <div class="col-sm-8">
      <h3>Java Basics</h3>
	  <h2>The Way Java Works</h2>
      <p>The goal is to write one application example and it will work on whatever devices which has the java supported operating systems such as windows,
			Mac Os and various versions of UNIX Operating Systems.</p>
	  </br><p>The Source Code is written and compiled in one type of operating System.After Compilation the Byte-Code of the Source is generated.
	  <br><p>The generated Byte-Code is can be executed in the same or in the different machine. If the other machine in which the Byte-Code needs to be executed
				does not have Java Development tools and Features.It is ok, just the machine needs to create JVM(Java Virtual Machine).JVM can be created if the machine has JRE installed.
				(Java RunTime Environment).</p>
	  <br><p>Java is a high-level programming language originally developed by Sun Microsystems and released in 1995. </p>
	  <p>Now Various versions of Java is available and owned by Oracle.
    </div>
<div>
<?php include 'javafooter.php';?>
</div>